'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'''

numlist = [1,1]
lim = 4000000
i=0
count = 0
while i<lim:
    numlist.append(numlist[-1]+numlist[-2])
    i=numlist[-1]
    count+=1
print (numlist)
numlist = [i for i in numlist if i%2 == 0]
print (numlist)
print (sum(numlist),count)
