'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'''
# ================= Check Version 2 for a better script =================
numlist = list()
x = 0
y = 1
temp = 0
user = input ('How many term? - ')

for i in range(1,int(user)+1):
    x=x+y
    y=x+y
    #print ('x is now:', x)
    #print ('y is now:', y)
    if x%2==0 and x<4000000: numlist.append(x)
    if y%2==0 and y<4000000: numlist.append(y)

for k in numlist:
    temp += k

print (numlist)
print (temp)
