'''http://www.practicepython.org/exercise/2014/07/05/18-cows-and-bulls.html
Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game!
  Enter a number:
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number.
;
NOTEs ON MAIN METHOD ARE ALSO EXPLAINED IN THIS TOPIC
    if __name__=="__main__":'''

import random
import string

print('INITIAL "COWS AND BULLS"...')

num = string.digits
PASS = ''
def Create4():  #This function randomly generate a 4-digit number
    global PASS, num
    a = random.choices(num, k=4)
    for i in a:
        PASS+=i
    return PASS # a string of 4 digits
def User(text='Your guess? - '): #Prompt for guesses
    while True:
        guessed = input(text)
        if len(guessed)!=4:
            print("Invalid input, please try again")
            continue
        else:
            print ('Checking', guessed,"...\n")
            return guessed # a string of 4 digits

correct_place = 0
wrong_place = 0
count = 0
def Cow_Bull():
    global correct_place,wrong_place,count
    PASS = Create4()
    print ("PASS generated!")
    while correct_place<=3:
        count +=1 # Count number of trials
        correct_place = 0 # Count number of cows
        wrong_place = 0 # Count number of bulls
        temp = 0 # indices for PASS
        # tempPASS = PASS
        guessed = User()
        for loop in guessed:
            if loop == PASS[temp]:
                correct_place+=1
            elif loop in PASS:
                wrong_place+=1
                if guessed.count(loop)>PASS.count(loop):
                    wrong_place-=1
                    #prevent overlap in wrong_place. ex: 3311 in 5815 => wrong_place is 3
            temp+=1
        print("{0} Cow(s)  {1} Bull(s)\n".format(correct_place,wrong_place))
    print ("CONGRATULATION!")
    print ("You made it after {0} tries".format(count))
Cow_Bull()
