'''http://www.practicepython.org/exercise/2014/07/05/18-cows-and-bulls.html
Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game!
  Enter a number:
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number.'''
# I tried to use class in this script
import random
import string

print('INITIAL "COWS AND BULLS"...')

class Game:
    num = string.digits
    PASS = ''
    def Create4():  #This function randomly generate a 4-digit number
        a = random.choices(num, k=4)
        for i in a:
            PASS+=i
        return PASS
    def User(text='Your guess? - '): #Prompt for guesses
        guessed = input(text)
        if len(guessed)!=4:
            print("Invalid input, please try again: ")
            print("what?")
        else:
            print ('Checking', guessed,"...\n")
            return guessed
    guessed = User()
    correct = 0
    wrong = 0
    def Cow_Bull():
        PASS = Game.Create4()
        print ("PASS generated!")
        while correct<=3:
            correct = 0
            wrong = 0
            for number in guessed:
                if number in PASS:
                    correct+=1
                else:
                    wrong+=1
        print("{0} Cow(s)  {1} Bull(s)".format(correct,wrong))
Game.Cow_Bull()
